### ISSUE TITLE
Strand constructor violates loose coupling principle

### ISSUE THREAD

**Issue by xcwfwf44** [ProgrammingLife2016/PL5-2016#120]
One of the Strand constructors violates the loose coupling principle by being exposed to the implementation of the DataBase class. It uses a org.neo4j.graphdb.Node instance and some properties given to it in the DataBase class to construct itself.

https://github.com/ProgrammingLife2016/PL5-2016/blob/master/backEnd/src/main/java/genome/Strand.java#L54

**Comment by MatthijsRijlaarsdam** [comment]
I'm against these constructors as well, it will result in a lot of double work when you want to update a class. @Nogeenaccount is working on it I believe.
